name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-posix:
    name: Build (Linux & macOS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Create output directory
        run: mkdir -p dist

      - name: Build for macOS ARM64
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          mkdir -p dist/macos-arm64
          go build -o dist/macos-arm64/go-irl

      - name: Build for Linux x64
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p dist/linux-x64
          go build -o dist/linux-x64/go-irl

      - name: Build for Linux ARM64
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          mkdir -p dist/linux-arm64
          go build -o dist/linux-arm64/go-irl

      - name: Make POSIX binaries executable
        run: |
          chmod +x dist/macos-arm64/go-irl
          chmod +x dist/linux-x64/go-irl
          chmod +x dist/linux-arm64/go-irl

      - name: Create ZIP archives
        run: |
          cd dist
          zip -j go-irl-macos-arm64.zip macos-arm64/go-irl ../README.md
          zip -j go-irl-linux-x64.zip  linux-x64/go-irl ../README.md
          zip -j go-irl-linux-arm64.zip linux-arm64/go-irl ../README.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: posix-zips
          path: dist/*.zip

  build-windows:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Create output directory
        run: mkdir dist

      - name: Build for Windows x64
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          mkdir dist\windows-x64
          go build -o dist\windows-x64\go-irl.exe
          Compress-Archive -Path dist\windows-x64\go-irl.exe, README.md -DestinationPath dist\go-irl-windows-x64.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: dist/go-irl-windows-x64.zip
